name: Build Website App
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create Web Zip
        run: |
          mkdir -p output
          zip -r output/my-app-web.zip . -x "*.git*"
      - name: Upload Web Build
        uses: actions/upload-artifact@v4
        with:
          name: my-web-app
          path: output/my-app-web.zip
